application: ethercheckout
version: ethercheckout-tier-1
runtime: python27
api_version: 1
threadsafe: yes

# application_readable: true


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /flash
  static_dir: static/flash
  secure: always
  http_headers:
    Vary: Accept-Encoding

- url: /som
  static_dir: static/som
  secure: always
  http_headers:
    Vary: Accept-Encoding

- url: /fonts
  static_dir: static/fonts
  secure: always
  http_headers:
    Vary: Accept-Encoding
    Access-Control-Allow-Origin: '*'
    
- url: /lib
  static_dir: static/lib
  # expiration: "30d"
  secure: always
  http_headers:
    Vary: Accept-Encoding
    Access-Control-Allow-Origin: '*'

- url: /assets
  static_dir: static/assets
  # expiration: "30d"
  secure: always
  http_headers:
    Vary: Accept-Encoding
    Access-Control-Allow-Origin: '*'



- url: /css
  static_dir: static/css
  secure: always
  http_headers:
    Vary: Accept-Encoding
    Access-Control-Allow-Origin: '*'

- url: /js
  static_dir: static/js
  secure: always
  http_headers:
    Vary: Accept-Encoding
    Access-Control-Allow-Origin: '*'


- url: /images
  static_dir: static/images
  secure: always
  expiration: "30d"
  http_headers:
    Vary: Accept-Encoding


- url: /img
  static_dir: static/img
  secure: always
  # expiration: "30d"
  http_headers:
    Vary: Accept-Encoding


- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
  http_headers:
    Vary: Accept-Encoding

    

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: yaml
  version: latest

- name: lxml
  version: latest

- name: jinja2
  version: latest

inbound_services:
- mail_bounce
- mail

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- .idea/*
- .git/*
- .devel/*

- .dist-info
- .egg-info